services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
        #- "80:80"
        #- "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back:/var/www/laravel
    depends_on:
      - mysql
      - php
    restart: always
    container_name: nginx

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./back:/var/www/laravel
    restart: always
    container_name: php

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    container_name: mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    container_name: phpmyadmin

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./back:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./back:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

  scheduler:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./back:/var/www/laravel
    entrypoint: [ "php", "/var/www/laravel/artisan", "schedule:work"]
    restart: unless-stopped


  elasticsearch:
    env_file:
      - env/elastic.env
    extends:
      file: docker-compose.elastic.yaml
      service: elasticsearch

  kibana:
    env_file:
      - env/elastic.env
    extends:
      file: docker-compose.elastic.yaml
      service: kibana
